### ISSUE TITLE
Investigate High CPU usage from docker containers

### ISSUE THREAD

**Issue by pamtaro** [microsoft/electionguard-web-api#107]
## Generic Issue

- [x] Ensure this issue is not a bug report or feature request

**Description**
Docker images are running at very high CPU usage even when not handling any requests. ~This has not been observed in MacOS.~ It is consistently an issue in Ubuntu running in WSL, but is potentially also an issue in just standalone Linux servers in general (need to confirm). 

**Possible Solution**
Unsure - needs more investigaiton

**Additional context/Screenshots**
when idle:
![image](https://user-images.githubusercontent.com/1423355/94597118-23c00b80-025b-11eb-9b88-e9718ceac214.png)

when processing requests:
![image](https://user-images.githubusercontent.com/1423355/94582474-45fd5d80-024a-11eb-8863-75191c544a93.png)
we have also observed CPU Usage up to 700%

**Comment by CuriousCurmudgeon** [comment]
For comparison, I'm currently seeing CPU usage of ~50-65% on MacOS while not handling any requests. That also seems high for an idle state though.

**Comment by pamtaro** [comment]
I'm getting around ~40-70% when idle 🤔 ... so maybe MacOS does also have this problem?

**Comment by keithrfung** [comment]
This could be related to #80 . We're being forced to use `--reload` which may be causing performance issues as stated in this [issue](https://github.com/tiangolo/fastapi/issues/295).

**Comment by pamtaro** [comment]
That seems right! When I query the processes running in the container, it's definitely due to `uvicorn`

**Comment by keithrfung** [comment]
Closed with previous uvicorn fixes
