### ISSUE TITLE
Creating Trustees should not return Trustee Private Keys

### ISSUE THREAD

**Issue by AddressXception** [microsoft/electionguard-web-api#14]
when setting up an election and creating trustees, it may not be desirable to return the complete trustee state across the API boundary.  We should provide an api endpoint that is capable of caching the state without returning the result across HTTP so that we can reduce the incidents of private data in motion.

To support compatibility both api's should exist

**Comment by keithrfung** [comment]
API moving to python this issue will become obsolete.
